@----------------------------------------------------------------------------
@ scaling.s - tile-domain 1.5x scaling for Jagoomba Color
@ (design journal maintained outside this repo)
@
@ Phase 0 (current): clean toggle support only.
@   scaling_restore - full rebuild of tiles + BG maps, called from the UI
@   when scaling is switched off, so anything the scaled mode clobbered in
@   VRAM is regenerated by the normal Mode 0 renderer.
@
@ Phase 1 (next): 2 GBC tiles -> 3 GBA tiles NN expansion, pair cache,
@   64x32 output map.
@----------------------------------------------------------------------------

	.pushsection .text, "ax", %progbits
	.arm
	.align 2

	global_func scaling_restore	@STT_FUNC needed for Thumb C -> ARM interworking

@----------------------------------------------------------------------------
@ scaling_restore - called from C (ui.c changescale) when scaling turns off.
@ Marks all tiles and both BG maps dirty, then re-renders them synchronously.
@ Same recipe as AfterLoadState (state.s). Safe to call from UI context:
@ the game is paused and we are outside the vblank handler.
@----------------------------------------------------------------------------
scaling_restore:
	stmfd sp!,{r3-r11,lr}
	ldr r10,=GLOBAL_PTR_BASE

	@v26: clear deferred queues FIRST - a stale RECENT_TILES snapshot (or
	@packet list) consumed after the rebuild would replay old tile data
	@over it with no pending invalidation = permanent corruption (S2)
	mov r0,#0
	strb_ r0,consume_buffer
	strb_ r0,consume_dirty
	ldr r1,=RECENT_TILENUM
	str r0,[r1]
	mov r1,#0
	ldr r0,=vram_packets_incoming
	mov r2,#0xC0
	bl_long memset32_
	ldr r0,=vram_packets_registered_bank0
	mov r2,#0xC0
	bl_long memset32_
	ldr r0,=vram_packets_registered_bank1
	mov r2,#0xC0
	bl_long memset32_
	ldr r0,=vram_packets_dirty
	mov r2,#0xC4
	bl_long memset32_

	@make VRAM all dirty
	mov r1,#0xFFFFFFFF
	ldr r0,=DIRTY_TILE_BITS
	mov r2,#48
	bl_long memset32_
	ldr r0,=dirty_map_words
	mov r2,#64
	bl_long memset32_

	@rebuild tile data and both tilemaps
	bl_long render_dirty_tiles
	bl_long render_dirty_bg

	ldmfd sp!,{r3-r11,lr}
	bx lr

	.ltorg
	.popsection
