@----------------------------------------------------------------------------
@ scaling.s - tile-domain 1.5x scaling for Jagoomba Color
@ Design: spec/SCALING_TILE_PLAN.md
@
@ Phase 0 (current): clean toggle support only.
@   scaling_restore - full rebuild of tiles + BG maps, called from the UI
@   when scaling is switched off, so anything the scaled mode clobbered in
@   VRAM is regenerated by the normal Mode 0 renderer.
@
@ Phase 1 (next): 2 GBC tiles -> 3 GBA tiles NN expansion, pair cache,
@   64x32 output map.
@----------------------------------------------------------------------------

	.pushsection .text, "ax", %progbits
	.arm
	.align 2

	global_func scaling_restore	@STT_FUNC needed for Thumb C -> ARM interworking

@----------------------------------------------------------------------------
@ scaling_restore - called from C (ui.c changescale) when scaling turns off.
@ Marks all tiles and both BG maps dirty, then re-renders them synchronously.
@ Same recipe as AfterLoadState (state.s). Safe to call from UI context:
@ the game is paused and we are outside the vblank handler.
@----------------------------------------------------------------------------
scaling_restore:
	stmfd sp!,{r3-r11,lr}
	ldr r10,=GLOBAL_PTR_BASE

	@make VRAM all dirty
	mov r1,#0xFFFFFFFF
	ldr r0,=DIRTY_TILE_BITS
	mov r2,#48
	bl_long memset32_
	ldr r0,=dirty_map_words
	mov r2,#64
	bl_long memset32_

	@rebuild tile data and both tilemaps
	bl_long render_dirty_tiles
	bl_long render_dirty_bg

	ldmfd sp!,{r3-r11,lr}
	bx lr

	.ltorg
	.popsection
